### ISSUE TITLE
add google map option to locate the shop

### ISSUE THREAD

**Issue by KevinJoseP** [KevinJoseP/TJ_Landing_Page#5]

**Comment by heloproc** [comment]
To add a Google Maps option to locate the shop in the HTML code, you can use an iframe tag with the embedded map. Here's an example of how you can add it:

`<!DOCTYPE html>

<head>



</head>

<body>





<iframe src="https://www.google.com/maps /embed?pb=!1m18!1m12!1m3!1d12345.678 9!2dlongitude!3dlatitude!4m22!3m21!1s0x0 %3A0x0!2sTJ%20Distributors!4m6!1m3!2m 2!1dlongitude!2dlatitude!1m6!1m2!1s0x0 %3A0x0!2sTJ%20Distributors!2sAddress %20of%20TJ%20Distributors!3m1!1s0x0: 0x0!5e0!3m2!1sen!2sus!4v1636175912345 !5m2!1sen!2sus" width="600" height="450" style="border:0;" allowfullscreen="

loading="lazy"></iframe>

</body>

</html>`

Replace "longitude" and "latitude" with the actual coordinates of the shop's location. Also, undate "Address%20of%201%20Distributors" with right address.
